"""add_intelliforge_2_0_incident_columns

Revision ID: c9f1581d8327
Revises: 
Create Date: 2026-08-12 19:37:02.497837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f1581d8327'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new columns as nullable first
    op.add_column('incidents', sa.Column('risk_score', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('confidence', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('endpoint_id', sa.String(length=100), nullable=True))
    op.add_column('incidents', sa.Column('correlation_id', sa.String(length=100), nullable=True))

    # Backfill sensible default values for pre-existing 37+ incident records
    op.execute("UPDATE incidents SET risk_score = 90 WHERE severity = 'Critical' AND risk_score IS NULL;")
    op.execute("UPDATE incidents SET risk_score = 70 WHERE severity = 'High' AND risk_score IS NULL;")
    op.execute("UPDATE incidents SET risk_score = 45 WHERE severity = 'Medium' AND risk_score IS NULL;")
    op.execute("UPDATE incidents SET risk_score = 20 WHERE risk_score IS NULL;")
    op.execute("UPDATE incidents SET confidence = 90 WHERE confidence IS NULL;")
    op.execute("UPDATE incidents SET endpoint_id = 'EP-MOHITH-PC-01' WHERE endpoint_id IS NULL;")



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'correlation_id')
    op.drop_column('incidents', 'endpoint_id')
    op.drop_column('incidents', 'confidence')
    op.drop_column('incidents', 'risk_score')
    # ### end Alembic commands ###
